name: done_yandex_app
description: A new Flutter project.
version: 0.1.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  build_runner: ^2.2.0
  flutter:
    sdk: flutter     
  flutter_localizations:
    sdk: flutter
  freezed: ^2.1.0+1
  json_annotation: ^4.6.0
  flutter_bloc: ^8.0.1
  provider: ^6.0.2
  flutter_secure_storage: ^5.0.2
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.0.2
  freezed_annotation: ^2.1.0
  dio: ^4.0.6
  hive: ^2.2.3
  uuid: ^3.0.6
  sliver_tools: ^0.2.7
  intl: ^0.17.0
  flutter_svg: ^1.1.3
  google_fonts: ^3.0.1
  firebase_core: ^1.20.0
  firebase_crashlytics: ^2.8.6
  firebase_remote_config: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1
  flutter_launcher_icons: ^0.9.3
  flutter_gen_runner: ^4.3.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

flutter_gen:
  output: lib/src/generated/
  style: camel-case
  integrations:
    flutter_svg: true 
